# metadata del entorno

Project=UI Automation
Module=Authentication & Forms
Environment=QA
BaseURL=https://the-internet.herokuapp.com
AppVersion=Demo
Browser=Chrome
Browser.Version=Latest
OS=Windows 11
Automation.Framework=Pytest + Pytest-BDD + Selenium
Reporting=Allure
Execution.Type=Local